version: '2.1'
volumes:
   files:
     driver: local
   mysql:
     driver: local
   backup:
     driver: local
   redis:
     driver: local
services:
   owncloud:
     image: owncloud/server:${OWNCLOUD_VERSION}
     restart: always
     ports:
       - ${HTTP_PORT}:8080
     depends_on:
       - db
       - redis
     environment:
       - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
       - OWNCLOUD_DB_TYPE=${OWNCLOUD_DB_TYPE}
       - OWNCLOUD_DB_NAME=${OWNCLOUD_DB_NAME}
       - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
       - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
       - OWNCLOUD_DB_HOST=${OWNCLOUD_DB_HOST}
       - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
       - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
       - OWNCLOUD_MYSQL_UTF8MB4=${OWNCLOUD_MYSQL_UTF8MB4}
       - OWNCLOUD_REDIS_ENABLED=${OWNCLOUD_REDIS_ENABLED}
       - OWNCLOUD_REDIS_HOST=${OWNCLOUD_REDIS_HOST}
     healthcheck:
       test: ["CMD", "/usr/bin/healthcheck"]
       interval: 30s
       timeout: 10s
       retries: 5
     volumes:
       - ./files:/mnt/data
   db:
     image: webhippie/mariadb:latest
     restart: always
     environment:
       - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
       - MARIADB_USERNAME=${OWNCLOUD_DB_USERNAME}
       - MARIADB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
       - MARIADB_DATABASE=${OWNCLOUD_DB_NAME}
       - MARIADB_MAX_ALLOWED_PACKET=32000M
       - MARIADB_INNODB_LOG_FILE_SIZE=32000M
     healthcheck:
       test: ["CMD", "/usr/bin/healthcheck"]
       interval: 30s
       timeout: 10s
       retries: 5
     volumes:
       - ./mysql:/var/lib/mysql
       - ./backup:/var/lib/backup
   redis:
     image: webhippie/redis:latest
     restart: always
     environment:
       - REDIS_DATABASES=1
     healthcheck:
       test: ["CMD", "/usr/bin/healthcheck"]
       interval: 30s
       timeout: 10s
       retries: 5
     volumes:
       - ./redis:/var/lib/redis